# Generated by Django 5.2.5 on 2025-08-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('country', models.CharField(db_column='tx_country', max_length=40)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('birth_date', models.DateField(db_column='tx_birth_date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('category', models.CharField(db_column='tx_category', max_length=40)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('profile', models.TextField(db_column='tx_profile')),
                ('limit_delivery', models.IntegerField(db_column='tx_limit_delivery', null=True)),
                ('name', models.CharField(db_column='tx_name', max_length=240)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=120)),
                ('publication_date', models.DateField(db_column='tx_publication_date')),
                ('quantity', models.IntegerField(db_column='tx_quantity')),
                ('author', models.ManyToManyField(db_table='book_author', to='core.author')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('cpf', models.IntegerField(db_column='tx_cpf')),
                ('date_birth', models.DateField(db_column='tx_birth_date')),
                ('status', models.IntegerField(db_column='tx_status')),
                ('profile', models.ManyToManyField(db_table='user_profile', to='core.profile')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('number', models.IntegerField(db_column='tx_number')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('loan', models.DateField(db_column='tx_loan')),
                ('date_withdraw', models.DateField(db_column='tx_date_withdraw')),
                ('date_return', models.DateField(db_column='tx_date_return')),
                ('delivery_time', models.TimeField(db_column='tx_delivery_time')),
                ('quantity', models.IntegerField(db_column='tx_quantity')),
                ('book', models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.PROTECT, to='core.book')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('address', models.CharField(db_column='tx_address', max_length=60)),
                ('cep', models.CharField(db_column='tx_cep', max_length=120)),
                ('public_place', models.CharField(db_column='tx_public_place', max_length=40)),
                ('reference_point', models.CharField(db_column='tx_reference_point', max_length=40)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
    ]
