# Generated by Django 5.2.5 on 2025-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(db_column='tx_cpf', max_length=11),
        ),
    ]
