# Generated by Django 5.2.5 on 2025-08-29 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('funcao', models.TextField(db_column='tx_funcao')),
                ('name', models.CharField(db_column='tx_name', max_length=240)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employee',
                'db_table': 'employee',
            },
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(db_column='tx_number', validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(db_column='tx_name', max_length=120)),
                ('cpf', models.CharField(db_column='tx_cpf', validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)])),
                ('date_birth', models.DateField(db_column='tx_birth_date')),
                ('status', models.IntegerField(db_column='tx_status')),
                ('funcao', models.ManyToManyField(db_table='user_funcao', to='core.function')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employee',
            },
        ),
    ]
