# Generated by Django 5.2.5 on 2025-08-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_function_alter_phone_number_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(db_column='id_employee', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.employee'),
        ),
    ]
